#!/usr/bin/env python3
"""Check AsyncRT ABI symbol parity in both directions.

Every `AsyncRT_*` name Mojo reaches through `external_call` must be defined by
our runtime, or the first build that reaches that path fails to link. The
reverse direction is reported but not failed: an ABI may legitimately offer
more than one tree uses.

This is a script rather than a bazel test on purpose -- the scan crosses the
whole Mojo tree, which is not a dependency a test target can express honestly.

The trap that makes a naive version of this useless: Mojo formats most of these
with the symbol on the line AFTER `external_call[`, so a same-line grep finds a
small fraction and quietly reports success. The scan below is multi-line.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RUNTIME = ROOT / "AsyncRT" / "lib" / "MojoBindings"
MOJO_TREES = [ROOT / "max", ROOT / "mojo"]

# `external_call[` then, possibly after a newline and indentation, "SYMBOL".
CALL_RE = re.compile(r'external_call\s*\[\s*"(AsyncRT_[A-Za-z0-9_]+)"', re.S)
# Definitions: plain extern "C" functions and every VR_STUB_* macro form.
# Note the return type is usually clang-format-wrapped onto its own line, so
# `extern "C"` and the symbol are NOT on the same line -- the gap may contain
# newlines, but never `{` or `;`, which is what bounds the match. Headers are
# excluded so a match means a definition; a symbol declared but never defined
# is the linker's job to catch, not this script's.
DEF_RE = re.compile(
    r'(?:extern\s+"C"[^{;]*?\b(AsyncRT_[A-Za-z0-9_]+)\s*\()'
    r'|(?:VR_STUB_(?:ERR|VOID|ZERO|[A-Z0-9_]+)\s*\(\s*(AsyncRT_[A-Za-z0-9_]+))',
    re.S,
)


STUB_RE = re.compile(r'VR_STUB_(ERR|VOID|ZERO)\s*\(\s*(AsyncRT_[A-Za-z0-9_]+)')
STUB_MEANING = {
    "ERR": "stub — returns “not implemented”",
    "VOID": "stub — no-op",
    "ZERO": "stub — returns 0",
}


def classify(paths):
    """Map each defined symbol to what it actually DOES when called.

    A hand-maintained status column is wrong the moment someone implements a
    stub and forgets the doc, and a capability table nobody trusts is worse
    than none -- the whole point is to say what an entry point will do BEFORE
    you call it.
    """
    kinds = {}
    for base in paths:
        for path in base.rglob("*"):
            if path.suffix not in {".cpp", ".mm"} or not path.is_file():
                continue
            text = path.read_text(errors="ignore")
            for macro, name in STUB_RE.findall(text):
                kinds[name] = STUB_MEANING[macro]
            for match in DEF_RE.finditer(text):
                name = next(g for g in match.groups() if g)
                kinds.setdefault(name, "implemented")
    return kinds


def scan(paths, pattern, suffixes):
    found = {}
    for base in paths:
        for path in base.rglob("*"):
            if path.suffix not in suffixes or not path.is_file():
                continue
            try:
                text = path.read_text(errors="ignore")
            except OSError:
                continue
            for match in pattern.finditer(text):
                name = next(g for g in match.groups() if g)
                found.setdefault(name, path.relative_to(ROOT))
    return found


called = scan(MOJO_TREES, CALL_RE, {".mojo"})
defined = scan([RUNTIME], DEF_RE, {".cpp", ".mm"})

kinds = classify([RUNTIME])

if "--table" in sys.argv:
    rows = sorted(set(called) | set(defined))
    out = ["<!-- GENERATED by tools/check-abi-symbols.py --table; do not edit -->",
           "",
           "Regenerate with `python3 tools/check-abi-symbols.py --table`.",
           "",
           "The granularity here is the *symbol*, which is the honest limit of",
           "what can be generated: `implemented` means the entry point does real",
           "work, not that every argument to it resolves. `getAttribute` is the",
           "case to remember -- it is implemented, and most attribute codes still",
           "come back unsupported on Metal.",
           "",
           "| symbol | what it does when called | called from Mojo |",
           "|---|---|---|"]
    for name in rows:
        status = kinds.get(name, "**NOT DEFINED**")
        out.append(f"| `{name}` | {status} | {'yes' if name in called else 'no'} |")
    impl = sum(1 for n in rows if kinds.get(n) == "implemented")
    out += ["", f"{impl} implemented, {len(rows) - impl} stubbed or missing, "
                f"of {len(rows)} symbols across both directions."]
    notes = ROOT / "AsyncRT" / "lib" / "MojoBindings" / "ABI-NOTES.md"
    text = notes.read_text()
    # Cut at whichever marker this file still carries: the original hand-written
    # census on the first run, the generated heading on every run after. Without
    # the second the generator eats its own marker and can only ever run once.
    for marker in ("# All called symbols (census):", "# Capability table"):
        head, sep, _ = text.partition(marker)
        if sep:
            break
    assert sep, "no census or capability-table marker found in ABI-NOTES.md"
    notes.write_text(head + "# Capability table\n\n" + "\n".join(out) + "\n")
    print(f"ABI-NOTES.md capability table regenerated: {impl}/{len(rows)} implemented")
    sys.exit(0)

print(f"external_call sites reaching AsyncRT: {len(called)}")
print(f"symbols defined by the runtime:       {len(defined)}")

missing = sorted(set(called) - set(defined))
extra = sorted(set(defined) - set(called))

if extra:
    print(f"\ndefined but never called ({len(extra)}) -- reported, not failed:")
    for name in extra:
        print(f"  {name}")

if missing:
    print(f"\nMISSING -- called from Mojo, not defined ({len(missing)}):")
    for name in missing:
        print(f"  {name}  <- {called[name]}")
    sys.exit(1)

print("\nparity OK: every symbol Mojo calls is defined.")
